version: "3"

services:

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
    networks:
      - mynetwork

  datastore:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - mynetwork
  
  tweet_collection:
    build: ./tweet_collection
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - mynetwork
    command: ["./wait-for-it.sh", "-t", "0", "rabbitmq:5672", "--", "go", "run", "collect_publish.go"]
    

  sentiment_analysis:
    build: ./sentiment_analysis
    depends_on:
      - rabbitmq
      - datastore
    networks:
      - mynetwork
    command: ["./wait-for-it.sh", "-t", "0", "rabbitmq:5672", "--" ,"python", "sentiment.py"]

  frontend:
    build: ./frontend
    depends_on:
      - datastore
    ports:
      - 3000:3000
    networks:
      - mynetwork
    command: ["./wait-for-it.sh", "-t", "0", "rabbitmq:5672", "--" ,"python", "front_end.py"]

networks: 
  mynetwork:

